name: Build And Release

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
    - 'v*'  

jobs:
  test_and_buid:
    name: Test and Build 
    runs-on: ubuntu-latest
    steps:
      # Should replace with testing here, keeping get_version and build_zip as they should at least throw some errors if they fail
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version1
        run: echo ::set-output name=version::testing

      - name: Echo version
        run: |
          echo Version ${{ steps.get_version1.outputs.version }}

      - name: Make zip file
        id: build_zip1
        run: |
          mkdir build -p
          sed -i 's/MapViewer.Version = "0.0.0"/MapViewer.Version = "${{ steps.get_version1.outputs.version }}"/g' FR_Map_Viewer.xml
          zip --junk-paths build/FR_Map_Viewer.mpackage README.md FR_Map_Viewer.xml LICENSE config.lua map.json

      - uses: actions/upload-artifact@v2
        with:
          name: FR_Map_Viewer.mpackage
          path: build/FR_Map_Viewer.mpackage
      

      # if workflow was triggered due to a push, then that means we also got a v tag, and can create a release
  release:
    needs: test_and_buid
    name: Create Release if tagged
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version2
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}

      - name: Update version files
        run: |
          python update_versions.py --update_version --version ${{ steps.get_version2.outputs.version }}
      - name: Commit version files back to repo
        run: |
          git add versions.*
          git commit -m "[ci] Updated Versions" &> /dev/null 
          git push origin main

      - name: Make zip file
        id: build_zip2
        run: |
          mkdir build -p
          sed -i 's/MapViewer.Version = "0.0.0"/MapViewer.Version = "${{ steps.get_version2.outputs.version }}"/g' FR_Map_Viewer.xml
          zip --junk-paths build/FR_Map_Viewer.mpackage README.md FR_Map_Viewer.xml LICENSE config.lua map.json
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/FR_Map_Viewer.mpackage
          asset_name: FR_Map_Viewer.mpackage
          asset_content_type: application/zip